# Generated by Django 6.0 on 2025-12-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=20),
        ),
    ]
